author:
  institution: "TAFE WA North Metropolitan"
  website: "https://www.northmetrotafe.wa.edu.au"
  studentID: "20111176"
  note: This app made for ICT40120_Assessment03 present car park using MQTT

alias:
  - &app_font "Arial"
  - &small_font 30
  - &middle_font 40
  - &big_font 50
  - &welcome_font 120
  - &max_bays 150
  - &button_state_default "disabled"


app_info:
  version: "1.0.0"
  git_repo: "https://github.com/yacmov/TAFE_ICT40120_Assessment03/"
  title: "SMART CAR PARK"

title_frame:
  title_label: "â‡ SMART CAR PARK â‡"
  title_font: *app_font
  title_font_size: *big_font

status_frame:
  message: "status comment"

display_frame:
  current_bays_icon: " ğŸ…¿ï¸ : " 
  max_byas: *max_bays
  display_font: *app_font
  display_font_size: *middle_font
  display_max_bay: *max_bays

weather:
  temp: "â˜€ï¸ "
  current: "28"
  celsius: "Â°C "
  font: *app_font
  font_size: *small_font
  weather_list: ["â˜€ï¸", "ğŸŒ¤ï¸", "â›…", "ğŸŒ¥ï¸", "ğŸŒ¦ï¸", "ğŸŒ§ï¸", "â›ˆï¸", "ğŸŒ©ï¸", "ğŸŒ¨ï¸", "â›„", "ğŸŒªï¸", "ğŸŒŠ"]


list_box:
  height: 23
  weather: "weather"
  car_in: "car_in"
  car_out: "car_out"

  


setup_option:
  frame_text: "SETUP"
  mqtt_broker_off: "ğŸ”´ MQTT BROKER OFF"
  mqtt_broker_on: ğŸŸ¢ MQTT BROKER ON 
  mqtt_sub_off: "ğŸ”´ MQTT SUB OFF"
  mqtt_sub_on:  "ğŸŸ¢ MQTT SUB ON "
  customer_ui_off: "ğŸ”´ CUSTOMER UI OFF"
  customer_ui_on: "ğŸŸ¢ CUSTOMER UI ON "


publisher_frame:
  frame_text: "SENSOR"
  button_state_default: *button_state_default
  incoming_car: "ğŸš˜ Incoming Car"
  outgoing_car: "Outgoing Car ğŸš˜"

auto_mode:
  frame_text: 'AUTO MODE'
  button_state_default: *button_state_default
  off_plate_number: "ğŸ”´ AUTO PLATE NUMBER"
  off_car_in: "ğŸ”´ AUTO CAR IN " 
  off_car_out: "ğŸ”´ AUTO CAR OUT"
  on_plate_number: "ğŸŸ¢ AUTO PLATE NUMBER"
  on_car_in: "ğŸŸ¢ AUTO CAR IN "
  on_car_out: "ğŸŸ¢ AUTO CAR OUT"

car_park_display:
  title: 'CUSTOMER DISPLAY'
  welcome_msg: 'WELCOME'
  welcome_font_size: *welcome_font
  available_bay: "AVAILABLE BAY"
  max_bay: *max_bays
  at: "At"
